const {readFileSync}=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const elements=new Map();
let stored={};
const element=id=>{if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',value:'',listeners:{},addEventListener(event,handler){this.listeners[event]=handler},querySelectorAll(){return []}});return elements.get(id)};
const sandbox={Intl,Set,localStorage:{getItem:()=>JSON.stringify(stored),setItem:(key,value)=>{stored=JSON.parse(value)}},document:{getElementById:element,addEventListener(){},querySelectorAll(){return []}}};
const context=vm.createContext(sandbox);
vm.runInContext(readFileSync('app.js','utf8'),context);
const run=code=>vm.runInContext(code,context);
assert.equal(run('currency'),'USD');
assert.equal(run('campaigns.flatMap(c=>filteredLeaves(c)).length'),18);
const both=run('aggregate(campaigns.flatMap(c=>filteredLeaves(c))).spend');
run("setAccountSelection(['demo-account-01'])");
const one=run('aggregate(campaigns.flatMap(c=>filteredLeaves(c))).spend');
assert.equal(run('campaigns.flatMap(c=>filteredLeaves(c)).length'),11);
assert(!element('entity-options').innerHTML.includes('AN_Leads_RO_Design_12_Iun'));
run("setAccountSelection(['demo-account-02'])");
const two=run('aggregate(campaigns.flatMap(c=>filteredLeaves(c))).spend');
assert(Math.abs(both-one-two)<0.001);
assert.throws(()=>run("setAccountSelection(['demo-account-01','demo-account-03'])"),/aceeași monedă/);
assert.equal(run('[...selectedAccounts].join()'),'demo-account-02');
run("setAccountSelection(['demo-account-03'])");
assert.equal(run('currency'),'EUR');
assert.equal(run('campaigns.flatMap(c=>filteredLeaves(c)).length'),2);
run("setAccountSelection(['demo-account-01','demo-account-04'])");
assert.equal(run('currency'),'USD');
assert.equal(run('campaigns.flatMap(c=>filteredLeaves(c)).length'),12);
run("selected.delete('demo-account-01:r0');setAccountSelection(['demo-account-02']);setAccountSelection(['demo-account-01']);");
assert.equal(run('campaigns.flatMap(c=>filteredLeaves(c)).length'),10);
run("dateTo='2026-06-10'");
assert(run('aggregate(campaigns.flatMap(c=>filteredLeaves(c))).spend')<one);
run("inactiveTags.add('demo-account-01:c1');tagFilter='exclude'");
assert.equal(run('campaigns.flatMap(c=>filteredLeaves(c)).length'),0);
run('setAccountSelection([])');
assert.equal(run('campaigns.flatMap(c=>filteredLeaves(c)).length'),0);
assert.equal(element('currency').textContent,'—');
assert.deepEqual(stored.selectedAccounts,[]);
assert.equal(run('new Set(allNodes.map(n=>n.id)).size'),run('allNodes.length'));
console.log('PASS: account isolation, additive totals, cross-portfolio selection, currency guard, retained creative choices, date/tag filters, empty selection, stable IDs and persistence.');
